Description: Certificates used by Cognito, API Gateway and other cross-cutting concerns for subdomains and root domains on the .com and .app domains

Parameters:
  TargetEnvironment:
    Description: 'Examples are local, dev, test, prod, etc'
    Type: 'String'
    
  ProductName:
    Description: 'Represents the name of the product you want to call the deployment'
    Type: 'String'

Conditions: 
  CreateProdResources: !Equals [ !Ref TargetEnvironment, prod ]
  
Resources:
  CertificateApiDomain:
      Type: AWS::CertificateManager::Certificate
      Properties:
          DomainName: !If [CreateProdResources, !Sub "api.${ProductName}.app", !Sub "${TargetEnvironment}-api.${ProductName}.app"]
          DomainValidationOptions:
            - DomainName:  !If [CreateProdResources, !Sub "api.${ProductName}.app", !Sub "${TargetEnvironment}-api.${ProductName}.app"]
              HostedZoneId:  {'Fn::ImportValue': !Sub '${ProductName}-route53-dotappzone'}
          ValidationMethod: DNS
          #SubjectAlternativeNames:
          #    - !If [CreateProdResources, !Sub "api.${ProductName}app.com", !Sub "${TargetEnvironment}-api.${ProductName}app.com"]
          Tags:
            - Key: environment
              Value: !Ref TargetEnvironment
            - Key: orchestration
              Value: cloud-formation
            - Key: service
              Value: api
            - Key: service-type
              Value: aws-managed
            - Key: product
              Value: !Ref ProductName
            
          
  CertificateAuthDomain:
    Type: AWS::CertificateManager::Certificate
    Properties:
        DomainName: !If [CreateProdResources, !Sub "auth.${ProductName}.app", !Sub "${TargetEnvironment}-auth.${ProductName}.app"]
        DomainValidationOptions:
          - DomainName:  !If [CreateProdResources, !Sub "auth.${ProductName}.app", !Sub "${TargetEnvironment}-auth.${ProductName}.app"]
            HostedZoneId:  {'Fn::ImportValue': !Sub '${ProductName}-route53-dotappzone'}
        ValidationMethod: DNS
        #SubjectAlternativeNames:
        #    - !If [CreateProdResources, !Sub "auth.${ProductName}app.com", !Sub "${TargetEnvironment}-auth.${ProductName}app.com"]
        Tags:
          - Key: environment
            Value: !Ref TargetEnvironment
          - Key: orchestration
            Value: cloud-formation
          - Key: service
            Value: auth
          - Key: service-type
            Value: aws-managed
          - Key: product
            Value: !Ref ProductName
          
Outputs:
  CertificateApiDomain:
    Description: 'ARN of the Certificate created for the api associated to the environment'
    Value: !Ref CertificateApiDomain
    Export:
      Name: !Sub '${ProductName}-${TargetEnvironment}-certificate-api'

  CertificateAuthDomain:
    Description: 'ARN of the Certificate created for auth with Cognito'
    Value: !Ref CertificateAuthDomain
    Export:
      Name: !Sub '${ProductName}-${TargetEnvironment}-certificate-auth'