Description: 'Hosted Zones to manage DNS for the domains consumed by the platform.'

Parameters:
  ProductName:
    Description: 'Represents the name of the product you want to call the deployment'
    Type: 'String'

Resources:
    FocusMarkDotAppZone:
      Type: AWS::Route53::HostedZone
      Properties:
        HostedZoneConfig:
          Comment: !Sub 'Hosted Zone for ${ProductName}.app'
        Name: !Sub '${ProductName}.app'
          
Outputs:
  FocusMarkDotAppZoneId:
    Description: 'HostedZone for the .app domain in Route 53'
    Value: !Ref FocusMarkDotAppZone
    Export:
      Name: !Sub '${ProductName}-route53-dotappzone'