Description: >-
  S3 buckets that are shared by cross-cutting concerns, such as deployment or logging. Buckets in this stack does not belong to any specific service within the platform, rather it is shared by many.

Parameters:
  TargetEnvironment:
    Description: 'Examples are local, dev, test, prod, etc'
    Type: 'String'
    
  ProductName:
    Description: 'Represents the name of the product you want to call the deployment'
    Type: 'String'

Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: aws:kms
      BucketName: !Sub "${ProductName}-${TargetEnvironment}-s3-logging"
      LifecycleConfiguration:
        Rules:
        - Id: AutoArchiveAndDelete
          Status: Enabled
          ExpirationInDays: '90'
          Transitions:
            - TransitionInDays: '30'
              StorageClass: GLACIER
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: environment
          Value: !Ref TargetEnvironment
  
  SAMDeploymentBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      BucketName: !Sub "${ProductName}-${TargetEnvironment}-s3-deployments"
      LifecycleConfiguration:
        Rules:
        - Id: AutoArchiveAndDelete
          Status: Enabled
          ExpirationInDays: '14'
          Transitions:
            - TransitionInDays: '7'
              StorageClass: GLACIER
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: !Sub "${ProductName}-${TargetEnvironment}-s3-deployments"
      Tags:
        - Key: environment
          Value: !Ref TargetEnvironment
        

Outputs:
  LogginBucket:
    Description: 'The bucket used to store and retain log files'
    Value: !Ref LoggingBucket
    Export:
      Name: !Sub '${ProductName}-${TargetEnvironment}-s3-logging'