AWSTemplateFormatVersion: 2010-09-09
Description: Allows CloudFormation templates to create a SecureString parameter into the SSM Parameter Store via a Lambda Function. This works around CloudFormation itself not support SecureString deployments.

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ProductName:
    Description: 'Represents the name of the product you want to call the deployment, such as FocusMark'
    Type: 'String'
    
  TargetEnvironment:
    Description: 'Represents the environment being deployed into, such as dev, test, prod or a feature branch environment.'
    Type: 'String'
    
Resources:
  FMSecureSecretFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProductName}-${TargetEnvironment}-lambda-fmSecureSecret'
      Handler: src/handler.run
      Runtime: nodejs12.x
      MemorySize: 256
      Timeout: 60
      Description: A function used to create Secure String parameters in the SSM Parameter Store as a CloudFormation custom Resource due to CloudFormation not supporting Secure Strings.
      Role: !GetAtt FMSecureSecretFunctionRole.Arn
      Environment:
        Variables:
          ManagingStack: !Ref AWS::StackId

  # IAM Role used by the SecureStringFunction Lambda
  FMSecureSecretFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'Allows for writing to CloudWatch and manipulating parameters in SSM Parameter Store.'
      RoleName: !Sub '${ProductName}-${TargetEnvironment}-role-fmSecureSecret'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ProductName}-${TargetEnvironment}-policy-fmSecureSecret'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:PutParameter'
                  - 'ssm:AddTagsToResource'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ssm:DeleteParameter'
                  - 'ssm:GetParameter'
                Resource: '*'
                Condition: # Only allow deletion of fetching of parameters that are tagged as having been created by the Lambda in this CF Stack.
                  StringLike:
                    ssm:ResourceTag/custom::fmsecuresecret: !Ref AWS::StackId
              - Effect: Allow
                Action: 
                  - 'xray:CreateGroup'
                  - 'xray:CreateSamplingRule'
                Resource: 
                  - 'arn:aws:xray:*:*:group/*/*'
                  - 'arn:aws:xray:*:*:sampling-rule/*'
              - Effect: Allow
                Action:
                  - 'xray:PutTelemetryRecords'
                  - 'xray:PutTraceSegments'
                Resource: '*'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        
Outputs:
  SecureStringFunctionArn:
    Description: "Secure String Custom Function ARN for use as a custom CloudFormation Resource"
    Value: !GetAtt FMSecureSecretFunction.Arn
    Export:
      Name: !Sub '${ProductName}-${TargetEnvironment}-lambda-fmSecureSecretFunction'