Description: >-
  S3 buckets that are shared by cross-cutting concerns, such as deployment or logging, across all environments.

Parameters:
    
  ProductName:
    Description: 'Represents the name of the product you want to call the deployment'
    Type: 'String'

Resources:
  GlobalLoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: aws:kms
      BucketName: !Sub "${ProductName}-global-s3-logging"
      LifecycleConfiguration:
        Rules:
        - Id: AutoArchiveAndDelete
          Status: Enabled
          ExpirationInDays: '90'
          Transitions:
            - TransitionInDays: '30'
              StorageClass: GLACIER
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: environment
          Value: global
        - Key: orchestration
          Value: cloud-formation
        - Key: service
          Value: audit
        - Key: service-type
          Value: aws-managed
        - Key: product
          Value: !Ref ProductName
          
  GlobalDeploymentBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      BucketName: !Sub "${ProductName}-global-s3-deployments"
      LifecycleConfiguration:
        Rules:
        - Id: AutoArchiveAndDelete
          Status: Enabled
          ExpirationInDays: '14'
          Transitions:
            - TransitionInDays: '7'
              StorageClass: GLACIER
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref GlobalLoggingBucket
        LogFilePrefix: !Sub "${ProductName}-global-s3-deployments"
      Tags:
        - Key: environment
          Value: global
        - Key: orchestration
          Value: cloud-formation
        - Key: service
          Value: devops
        - Key: service-type
          Value: aws-managed
        - Key: product
          Value: !Ref ProductName
          
Outputs:
  GlobalLogginBucket:
    Description: 'The bucket used to store and retain log files'
    Value: !Ref GlobalLoggingBucket
    Export:
      Name: !Sub '${ProductName}-global-s3-logging'